# Integrator-matched retraining experiment for the FHN closed-loop forecast.
#
# The FPGA word-length study found that a fixed-step integrator reaches only
# ~0.5 Lyapunov times vs 1.57 for the adaptive Tsit5 solver the readout was
# trained against. Hypothesis: the loss is a train/deploy mismatch -- the
# readout was trained on Tsit5-generated reservoir states but deployed on
# (slightly different) fixed-step states. This script tests whether training
# the readout on states generated by the *same* fixed-step integrator used at
# deployment recovers the horizon.
#
# Three conditions (all Float64, grid + near-bifurcation, seed 42):
#   A. Tsit5-trained readout      + Tsit5 closed loop       (1.57 reference)
#   B. Tsit5-trained readout      + fixed-step closed loop  (the mismatch)
#   C. fixed-step-trained readout + fixed-step closed loop  (matched -- the test)
#
# Run: julia +1.11 --project=. Reservoir-Computing-in-Julia/integrator_matched.jl

include("common.jl")
using .RCCommon
using Graphs
using LinearAlgebra
using Random
using Statistics
using OrdinaryDiffEq
using Flux

# --- config (matches RC_FHN_NN.jl best result) -------------------------------
const SEED = 42
n_nodes = 256
dim_system = 3
sigma_in = 1.5
washout = 500
dt = 0.01
delay_steps = 10
eps_fhn = 0.05
a_lo, a_hi = 0.95, 1.1
coupling = 0.3
R0 = 0.5
speed = 20.0
epochs = 400
batchsize = 256
learning_rate = 1e-3
noise_level = 0.02f0
K_sub = 50
const d_steps = delay_steps

rng = MersenneTwister(SEED)
Random.seed!(SEED)

# --- reservoir ---------------------------------------------------------------
g = SimpleDiGraph(Graphs.grid([isqrt(n_nodes), isqrt(n_nodes)]))
N = nv(g)
Wc = zeros(N, N)
for e in edges(g)
    Wc[dst(e), src(e)] = 0.1 + 0.9 * rand(rng)
end
for i in 1:N
    s = sum(@view Wc[i, :])
    s > 0 && (Wc[i, :] .*= coupling / s)
end
in_strength = vec(sum(Wc, dims = 2))

function make_fhn_rhs(input)
    return function fhn!(dr, r, p, t)
        u = @view r[1:N]; w = @view r[(N + 1):2N]
        du = @view dr[1:N]; dw = @view dr[(N + 1):2N]
        gin = input(t)
        mul!(du, Wc, u)
        @. du = speed * (du - in_strength * u + u - u^3 / 3 - w + gin)
        @. dw = speed * eps_fhn * (R0 * gin + u - a_fhn)
        return nothing
    end
end

# --- data --------------------------------------------------------------------
train_data, t_train, test_data, t_test =
    generate_lorenz_split(t_train = 200.0, t_test = 25.0, dt = dt)
scaler = Standardizer(train_data)
u_train = transform(scaler, train_data)
W_in = 2 * sigma_in * (rand(rng, N, dim_system) .- 0.5)
a_fhn = a_lo .+ (a_hi - a_lo) .* rand(rng, N)

delay_features(S, idx) = vcat(S[:, idx], S[:, idx .- d_steps], S[:, idx .- 2d_steps])

# one explicit-RK2 substep set advancing the reservoir by dt with input gin held
function rk2_step(state, gin)
    dt_sub = dt / K_sub
    deriv(u, w) = (speed .* (Wc * u .- in_strength .* u .+ u .- u .^ 3 ./ 3 .- w .+ gin),
                   speed * eps_fhn .* (R0 .* gin .+ u .- a_fhn))
    for _ in 1:K_sub
        u = @view state[1:N]; w = @view state[(N + 1):2N]
        du1, dw1 = deriv(u, w)
        du2, dw2 = deriv(u .+ (dt_sub / 2) .* du1, w .+ (dt_sub / 2) .* dw1)
        state = vcat(u .+ dt_sub .* du2, w .+ dt_sub .* dw2)
    end
    return state
end

# --- training-data generation ------------------------------------------------
# (A/B) Tsit5 teacher-forced states: state at t_i, target u_train[i].
input_train = make_lerp(t_train, W_in * u_train')
sol = solve(ODEProblem(make_fhn_rhs(input_train), zeros(2N), (t_train[1], t_train[end])),
            Tsit5(); saveat = t_train, abstol = 1e-6, reltol = 1e-6)
R_tsit5 = Array(sol)
n_tr = size(R_tsit5, 2)
F_tsit5 = delay_features(R_tsit5, washout:n_tr)
Y_tsit5 = u_train[washout:n_tr, :]'

# (C) fixed-step teacher-forced states, generated EXACTLY as deployment steps:
# state_i is advanced by gin = W_in*u_train[i-1] (the previous true sample),
# and the readout target is u_train[i] -- the same alignment as the closed loop.
function generate_matched()
    state = zeros(2N)
    hist = zeros(2N, 2d_steps + 1)
    feats = Vector{Float64}[]; targs = Vector{Float64}[]
    for j in 2:n_tr
        state = rk2_step(state, W_in * u_train[j - 1, :])
        hist = hcat(hist[:, 2:end], state)
        if j > washout
            push!(feats, vcat(hist[:, end], hist[:, end - d_steps], hist[:, end - 2d_steps]))
            push!(targs, u_train[j, :])
        end
    end
    return reduce(hcat, feats), reduce(hcat, targs)
end
F_match, Y_match = generate_matched()

# --- readout training --------------------------------------------------------
function train_readout(F, Y)
    Xf = Float32.(F); Yt = Float32.(Y)
    model = Chain(Dense(6N => 256, tanh), Dense(256 => dim_system))
    opt_state = Flux.setup(Adam(learning_rate), model)
    loader = Flux.DataLoader((Xf, Yt); batchsize = batchsize, shuffle = true)
    for epoch in 1:epochs
        epoch == round(Int, 0.75 * epochs) && Flux.adjust!(opt_state, 1e-4)
        for (x, y) in loader
            xn = x .+ noise_level .* randn(Float32, size(x))
            _, gr = Flux.withgradient(m -> Flux.mse(m(xn), y), model)
            Flux.update!(opt_state, model, gr[1])
        end
    end
    return model, Flux.mse(model(Xf), Yt)
end

readout(model, f) = Float64.(model(Float32.(f)))

# --- deployment: fixed-step closed loop --------------------------------------
function fixedstep_forecast(model, R_seed)
    n_steps = length(t_test)
    pred = zeros(n_steps, dim_system)
    hist = copy(R_seed[:, (end - 2d_steps):end])
    state = copy(R_seed[:, end])
    x = u_train[end, :]
    for i in 1:n_steps
        state = rk2_step(state, W_in * x)
        hist = hcat(hist[:, 2:end], state)
        feats = vcat(hist[:, end], hist[:, end - d_steps], hist[:, end - 2d_steps])
        x = clamp.(readout(model, feats), -5.0, 5.0)
        pred[i, :] = x
    end
    return inverse_transform(scaler, pred)
end

# --- deployment: Tsit5 closed loop (condition A reference) -------------------
function tsit5_forecast(model)
    n_steps = length(t_test)
    g_ref = Ref(zeros(N))
    prob = ODEProblem(make_fhn_rhs(t -> g_ref[]), copy(R_tsit5[:, end]), (0.0, n_steps * dt))
    integ = init(prob, Tsit5(); abstol = 1e-6, reltol = 1e-6, save_everystep = false)
    pred = zeros(n_steps, dim_system)
    hist = copy(R_tsit5[:, (end - 2d_steps):end])
    x = u_train[end, :]
    for i in 1:n_steps
        g_ref[] = W_in * x
        step!(integ, dt, true)
        hist = hcat(hist[:, 2:end], integ.u)
        feats = vcat(hist[:, end], hist[:, end - d_steps], hist[:, end - 2d_steps])
        x = clamp.(readout(model, feats), -5.0, 5.0)
        pred[i, :] = x
    end
    return inverse_transform(scaler, pred)
end

# the matched readout needs a fixed-step seed state continuous with its own
# stepping; regenerate the final reservoir state via fixed-step teacher forcing
function fixedstep_seed()
    state = zeros(2N)
    R = zeros(2N, n_tr)
    for j in 2:n_tr
        state = rk2_step(state, W_in * u_train[j - 1, :])
        R[:, j] = state
    end
    return R
end
R_fixed = fixedstep_seed()

# --- paired multi-seed experiment --------------------------------------------
# Closed-loop valid time has large NN-initialization variance, so compare
# unmatched- vs matched-trained readouts with the SAME NN init per seed
# (paired), both deployed on the fixed-step integrator. This isolates the
# matched-training effect from init luck.
valid_time(X) = valid_prediction_time(test_data, X, t_test)[2]
nn_seeds = 1:5
println("seed | B: Tsit5-trained | C: matched-trained   (both fixed-step deploy, LT)")
tB = Float64[]; tC = Float64[]
for s in nn_seeds
    Random.seed!(s); mu, _ = train_readout(F_tsit5, Y_tsit5)
    Random.seed!(s); mm, _ = train_readout(F_match, Y_match)
    b = valid_time(fixedstep_forecast(mu, R_tsit5))
    c = valid_time(fixedstep_forecast(mm, R_fixed))
    push!(tB, b); push!(tC, c)
    println("  $s  |      $(round(b, digits=2))       |      $(round(c, digits=2))")
end
using Statistics: mean, std
println("\nUnmatched (B): $(round(mean(tB), digits=2)) ± $(round(std(tB), digits=2)) LT")
println("Matched   (C): $(round(mean(tC), digits=2)) ± $(round(std(tC), digits=2)) LT")
println("Mean paired gain from integrator-matched training: ",
        "$(round(mean(tC .- tB), digits=2)) LT")
